kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    enviroment:
      TESTSECRET:
        from_secret: test-secret
      TESTSECRETPULL:
        from_secret: test-secret-pull
    commands:
      - echo hello
      - echo world
      - echo $TESTSECRET
      - echo $TESTSECRETPULL
